/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_server.h"
#include "rpc_server_functions/rpc_server_functions.h"	// log_operation

pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;

void *
log_operation_1_svc(operation arg1, struct svc_req *rqstp)
{

	// Lock the mutex
	pthread_mutex_lock(&mutex);

	// Call the log_operation function
    log_operation(arg1.username, arg1.operation, arg1.timestamp);

	// Unlock the mutex
	pthread_mutex_unlock(&mutex);

	// Return 1 to avoid the RPC hanging when not receiving a non-error return value
    return (void *)1 ;
}

int
operationlog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
